#!/usr/bin/python

# This transforms takes a book or an article and retrieves the author information

from generic_transform import *

# load input article or book
e_type,e_values,params = get_from_args()

authors = e_values["authors"]

# authors are written in the format:
# <lastname1>, <firstname/initials1>; <lastname2>, <firstname/initials2>, ...
# we want to extract the first and last names
for author in authors.split("; "):
	lastname, firstname = author.split(", ")
	
	write_result("author", {"value": lastname, "firstname": firstname})
