#!/usr/bin/python

import sys
import requests
from bs4 import BeautifulSoup
from generic_transform import *

e_type,e_values,params = get_from_args()

phrase = e_values["value"]

phrase = "computer forensics"

p = {"q": phrase, "as_vis": "1"}
r = requests.get("http://scholar.google.com/scholar", params = p)

soup = BeautifulSoup(r.text)

res = soup.find_all(class_ = "gs_rt")
for r in res:
	if r.text[:6] != "[BOOK]":
		write_result("phrase", {"value": r.a.text})


